### ISSUE TITLE
Binaries from continuous integration builds

### ISSUE THREAD

**Issue by nokome** [stencila/pandoc#3]
We would like to provide binaries for Linux, MacOS and Windows users.

Windows builds are being done at https://ci.appveyor.com/project/nokome/pandoc with binary artifacts available at https://ci.appveyor.com/project/nokome/pandoc/build/artifacts

Linux and MacOS builds are being done at https://travis-ci.org/stencila/pandoc but no binary artifacts are being saved. See https://docs.travis-ci.com/user/deployment/s3/ for uploading to S3.

**Comment by nokome** [comment]
Currently `stencila/convert` is download the binaries from https://github.com/jgm/pandoc/releases. See:

https://github.com/stencila/convert/blob/master/src/helpers/pandoc.js#L6

We need to provide similar files from build of this repo.

This is a suggested approach to uploading artifacts based on what we do in the stencila/stencila repo:

```yaml
before_deploy:
  - |
    # Create a versioned folder for the build
    mkdir -p bucket/pandoc/$TRAVIS_COMMIT
    ### cp things into it here
    # Update the list of builds
    curl -s http://builds.stenci.la/pandoc/builds.txt > bucket/pandoc/builds.txt
    echo $TRAVIS_COMMIT >> bucket/pandoc/builds.txt

deploy:
  on:
    branch: builds
  skip_cleanup: true
  local_dir: bucket
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  bucket: builds.stenci.la
```

Ping @hamishmack
